### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by Chmieloo** [api-tools/okapi#2]
Insert set of CSS rules for dark mode.

**Comment by GabrielCoutz** [comment]
Hi @Chmieloo, to use CSS rules in dark/light mode u can write all CSS inside these medias:

```css
@media (prefers-color-scheme: dark) {
  /* dark mode rules */
}

@media (prefers-color-scheme: light) {
  /* light mode rules */
}
```

or write normal CSS, and only use these medias to change specific styles, like:
```css
.myDiv {
  background-color: white;
  color: black;
}

@media (prefers-color-scheme: dark) {
  .myDiv {
    background-color: #303030;
    color: #dbdbdb;
  }
}

```

Hope it helps =)
